### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by sateun1221** [yoroshikun/node-pck-audio-extractor#1]
spawn libs\quickbms\quickbms.exe ENOENT
Error: spawn libs\quickbms\quickbms.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
"Completed decoding audio!, you may find the output in the output folder"

**Comment by yoroshikun** [comment]
Have you installed the requirements by running setup.exe?

**Comment by alb3rtusja** [comment]
I got this message when running setup.cmd
any solution?

Failed to get 'https://f.losno.co/vgmstream-win32-deps.zip' (404)
Error: Failed to get 'https://f.losno.co/vgmstream-win32-deps.zip' (404)
    at RedirectableRequest.<anonymous> (C:\Users\MSI\Downloads\Compressed\node-pck-audio-extractor-main\deps\helpers\download.js:24:16)
    at RedirectableRequest.emit (events.js:375:28)
    at RedirectableRequest._processResponse (C:\Users\MSI\Downloads\Compressed\node-pck-audio-extractor-main\deps\node_modules\follow-redirects\index.js:380:10)
    at ClientRequest.RedirectableRequest._onNativeResponse (C:\Users\MSI\Downloads\Compressed\node-pck-audio-extractor-main\deps\node_modules\follow-redirects\index.js:56:10)
    at Object.onceWrapper (events.js:482:26)
    at ClientRequest.emit (events.js:375:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:375:28)

**Comment by yoroshikun** [comment]
Hi I have pushed an update to the deps installer, the https://f.losno.co/vgmstream-win32-deps.zip no longer works (404) so hopefully this patch fixes it.

Let me know how it goes. (delete the setup.exe) (please delete the deps folder first)
