### ISSUE TITLE
spawn libs\quickbms\quickbms.exe ENOENT

### ISSUE THREAD

**Issue by ceciEstErmat** [yoroshikun/node-pck-audio-extractor#4]
Does this project still work ? I have multiple problems.

During the setup : 
`Failed to get 'https://vgmstream-builds.s3-us-west-1.amazonaws.com/70d20924341e1df3e4f76b4c4a6e414981950f8e/windows/test.zip' (404)
Error: Failed to get 'https://vgmstream-builds.s3-us-west-1.amazonaws.com/70d20924341e1df3e4f76b4c4a6e414981950f8e/windows/test.zip' (404)
    at RedirectableRequest.<anonymous> (C:\work\node-pck-audio-extractor\deps\helpers\download.js:24:16)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest._processResponse (C:\work\node-pck-audio-extractor\deps\node_modules\follow-redirects\index.js:380:10)
    at RedirectableRequest._onNativeResponse (C:\work\node-pck-audio-extractor\deps\node_modules\follow-redirects\index.js:56:10)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)`
    
During the decode : 
`"This script will decode .pck files to .wav"
Enter option arguments (enter for default):
Found 54 pck files
spawn libs\quickbms\quickbms.exe ENOENT
Error: spawn libs\quickbms\quickbms.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
"Completed decoding audio!, you may find the output in the output   ##folder"`

**Comment by NaufalF22** [comment]
Yes it still work. somehow the setup failed to fully download the libs so you should install it one by one

**Comment by Kawaiivee** [comment]
I'm getting the same error. I tried visiting the link and got this. Where do I download the missing dependencies?
![image](https://github.com/user-attachments/assets/fbdf9ee6-593f-4908-abbe-52ad61ae3d08)
